# Changes here will be overwritten by Copier
_commit: 0.1.5
_src_path: gh:12rambau/pypackage
author_email: pierrick.rambaud49@gmai.com
author_first_name: Pierrick
author_last_name: Rambaud
author_orcid: 0000-0001-8764-5749
github_repo_name: pygadm
github_user: 12rambau
project_name: pyGADM
project_slug: pygadm
short_description:
  Easy access to administrative boundary defined by GADM from Python
  scripts
